name: CI

on:
  # 1) 直接 push 到 master
  push:
    branches: [ master ]
  # 2) 针对 master 的 Pull Request
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # 1. 拉取代码
      - uses: actions/checkout@v4

      # 2. 安装符合 pyproject.toml 中声明版本的 Python
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          cache: pip

      # 3. 安装 Hatch（只需要几秒）
      - name: Install Hatch
        run: python -m pip install --upgrade hatch

      # 4. 创建并更新 dev 环境，再运行测试脚本
      - name: Run tests via Hatch
        run: |
          hatch env create dev          # 第一次会安装依赖，后续命中 pip 缓存会很快
          hatch run dev:test            # 你的脚本；若你把 env 改名为 default 就写 hatch run test